---
title: "HPK_Animated_Plot"
author: "Nina Li"
date: "11/10/2020"
output: html_document
---
```{r}
library(ggplot2)
library(lubridate)
library(gganimate)
theme_set(theme_bw())
```

Get input data
```{r}
flow_data <- readRDS("D://Ninalty/Hydropeaking/RWork/HPK_RDS/HPK_sm/HPK_SM_Reversal_ct.rds")
```

Get one site
```{r}
flow_data2 <- flow_data$CLE

flow_data2 <- flow_data2[, c(1, 2, 3, 4, 7)]

flow_data2 <- flow_data2[flow_data2$yr == 2018, ]
```

function
```{r}
HPK_Q_plot <- function(df){
  
  df$datetime2 <- paste(df$datetime, " ", df$nhour, ":00:00", sep = "")
  df$datetime2 <- as.POSIXct(df$datetime2, format="%Y-%m-%d %H:%M:%S")
  
  ggplot()+geom_line(data = df, aes(x=datetime2, y=parameter_value, group=1), size=1, show.legend = FALSE) + 
    scale_x_datetime(date_breaks = "3 days")+ # this allows user to plot date x axis
    labs(x = "Time", y="Discharge (cfs)", color = "Type")+
    theme(panel.background = element_blank(),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(), 
          panel.border = element_rect(colour = "black", fill=NA),
          axis.title.x = element_text(size = 20), 
          axis.title.y = element_text(size = 20), 
          axis.text.x = element_text(angle = 0, size = 18), 
          axis.text.y = element_text(size = 18)) 
}
```


check the static plot
```{r}
p <- HPK_Q_plot(flow_data2[400:620,])
p
```

```{r}
p2 <- p + transition_reveal(datetime2)

anim_save("filenamehere.gif", p2)
```

