---
title: "HPK_Plot"
author: "Nina Li"
date: "8/24/2020"
output: html_document
---
Get the input data
```{r}
HPK_sM_Reversal_ct <- readRDS("D:/Ninalty/UCD_Hydropeaking/HPK_FlowData/HPK_RDS/HPK_CA/HPK_sm/HPK_SM_Reversal_cta2.rds")

#remove sites not needed
HPK_sM_Reversal_ct <- HPK_sM_Reversal_ct[!names(HPK_sM_Reversal_ct) %in% c("F57")] 
```


Defined function
```{r}
library(ggplot2)

tagpt_color <- c(NA, rgb(112,173,71, max=255), rgb(255,0,0, max=255), "black", rgb(46,117,182, max=255))

Reversal_Count_plot <- function(df){
  
  df$datetime2 <- paste(df$datetime, " ", df$nhour, ":00:00", sep = "")
  df$datetime2 <- as.POSIXct(df$datetime2, format="%Y-%m-%d %H:%M:%S")
  df$parameter_value <- df$parameter_value*0.028316847 # cfs to m3/s
  
  df$dgtag <- as.factor(df$dgtag)
  
  ggplot()+geom_line(data = df, aes(x=datetime2, y=parameter_value, group=1), size=0.7, show.legend = FALSE) + 
    geom_point(data = df, aes(x=datetime2, y=parameter_value, 
                              shape=factor(dgtag, levels = c(0,1,2,3,4)), 
                              fill=factor(dgtag, levels = c(0,1,2,3,4)), 
                              color=factor(dgtag, levels = c(0,1,2,3,4))), na.rm = TRUE,
                              size=4, show.legend = FALSE) +
    scale_shape_manual(values = c(20, 24, 16, 16, 23))+
    scale_color_manual(values = tagpt_color)+
    scale_fill_manual(values = tagpt_color)+
    scale_x_datetime(date_breaks = "4 days")+ # this allows user to plot date x axis
    labs(x = "Time", color = "Type")+
    ylab(expression(Discharge~(m^3/s))) + 
    theme(panel.background = element_blank(),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(), 
          panel.border = element_rect(colour = "black", fill=NA),
          axis.title.x = element_text(size = 28), 
          axis.title.y = element_text(size = 26), 
          axis.text.x = element_text(angle = 0, size = 24), 
          axis.text.y = element_text(size = 24)) 
}
```


```{r}
plot_file <- HPK_sM_Reversal_ct

for (i in 1:length(plot_file)) {
  
  kk <- plot_file[[i]]
  
  kk <- kk[500:1000,]
  
  sample_plot <- Reversal_Count_plot(kk)
}

ggsave(paste(unique(kk$location_id),"_Reversal.png"), plot = sample_plot, path = "D:/Ninalty/UCD_Hydropeaking/HPK_Imagery/HPK_HPKEventsTag/HPK_90%_plt/", width = 40, height = 20, units = "cm")

```

Time seris plot with discharge marked by classification
```{r}
HPK_sM_Reversal_ct <- readRDS("D:/Ninalty/Hydropeaking/RWork/HPK_RDS/HPK_SM_Reversal_ct.rds")

HPK_sM_Reversal_ct = HPK_sM_Reversal_ct[-which(names(HPK_sM_Reversal_ct) %in% c("F57", "SJA", "M11"))] 

HPK_sM_Reversal_ct <- do.call("rbind", HPK_sM_Reversal_ct)

# add the cluster tag to the data
HPK_sM_Reversal_ct <- HPK_sM_Reversal_ct[, c(1,2,4,5,7)]

HPK_sM_Reversal_ct <- left_join(HPK_sM_Reversal_ct, classed_hpk_fuzc[, c(8,9)], by="location_id")

ggplot() + geom_line(data = HPK_sM_Reversal_ct, 
                        aes(x = sub_grp_fuzc, y = parameter_value, color = as.factor(yr))) +
                        scale_color_viridis(discrete = TRUE, option = "D") + 
           labs(x = "Group", y="Pk No.", color = "Year") +
           theme(panel.background = element_blank(),
                 panel.grid.major = element_blank(), 
                 panel.grid.minor = element_blank(), 
                 panel.border = element_rect(colour = "black", fill=NA))

```


Metrics
Time series plot -- pk_no
```{r}
library(lubridate)

library(viridis)

HPK_Fuzy_metric <- df2[,c(1,4,5,7)] # include all pk_no

#remove SJA, F57
HPK_Fuzy_metric <- HPK_Fuzy_metric[!HPK_Fuzy_metric$location_id %in% c("SJA", "F57"),]

HPK_Fuzy_metric$Mth <- months(HPK_Fuzy_metric$datetime, abbreviate = TRUE)

HPK_Fuzy_metric <- left_join(HPK_Fuzy_metric, classed_hpk_fuzc[, c(8,9)], by="location_id")

#split data by location_id
HPK_Fuzy_metric = split(HPK_Fuzy_metric, HPK_Fuzy_metric$location_id)

#create a function to plot metrics for indivual site
pk_no_plot <- function(df){
 tt <- ggplot() + geom_boxplot(data = df, 
                        aes(x = Mth, y = pk_no, color = as.factor(yr))) +
                        scale_color_viridis(discrete = TRUE, option = "D") + 
           labs(x = "Month", y="Pk No.", color = "Year") +
           theme(panel.background = element_blank(),
                 panel.grid.major = element_blank(), 
                 panel.grid.minor = element_blank(), 
                 panel.border = element_rect(colour = "black", fill=NA))
 ggsave(paste(unique(df$location_id), "_Pkno.png", sep = ""), plot = tt, path = "D:/Ninalty/Hydropeaking/RWork/7HPK_Plot/Pk_No/", width = 40, height = 20, units = "cm")
}

lapply(HPK_Fuzy_metric, pk_no_plot)

```

Pair with the classification
```{r}

ggplot() + geom_boxplot(data = HPK_Fuzy_metric, 
                        aes(x = sub_grp_fuzc, y = pk_no, color = as.factor(yr))) +
                        scale_color_viridis(discrete = TRUE, option = "D") + 
           labs(x = "Group", y="Pk No.", color = "Year") +
           theme(panel.background = element_blank(),
                 panel.grid.major = element_blank(), 
                 panel.grid.minor = element_blank(), 
                 panel.border = element_rect(colour = "black", fill=NA))
```


