---
title: "Californi_ Hydropeaking_regime"
author: "Nina Li"
date: "11/11/2020"
output: html_document
---
```{r}
library(tidyverse)
library(ggplot2)
library(gganimate)
```


First, create fake dataset for the hydropeaking flow regime
```{r}
day1 <- rep(1, 24)
day2 <- rep(2, 24)
day3 <- rep(3, 24)
day4 <- rep(4, 24)
day5 <- rep(5, 24)
day6 <- rep(6, 24)
day7 <- rep(7, 24)

day <- c(day1,day2,day3,day4,day5,day6,day7)

nhour <- c(0:167)

# CA hydropeaking regime G1
parameter_value <- rep(c(70,70,55,40,25,10,10,10,10,10,25,40,55,70), 12)
parameter_value <- c(c(10,10,10,10,10,10,25,40,55,70), parameter_value)[1:168]

CA_HPK_G1 <- data.frame(day, nhour, parameter_value)
CA_HPK_G1$group <- rep("G1", 168)


# CA hydropeaking regime G2
parameter_value <- rep(c(10,10,10,10,10,10,10,10,10,37,64,91,91,91,91,91,91,64,37,10,10,10,10,10),7)

CA_HPK_G2 <- data.frame(day, nhour, parameter_value)
CA_HPK_G2$group <- rep("G2", 168)


# CA hydropeaking regime G3
parameter_value <- rep(c(c(10,10,10,10,10,25,40,55,55,40,25,10,10,10,10,10,25,40,55,55,40,25,10,10),
                        rep(10,24)),4)[1:168]

CA_HPK_G3 <- data.frame(day, nhour, parameter_value)
CA_HPK_G3$group <- rep("G3", 168)


# CA hydropeaking regime G3
parameter_value <- rep(c(c(10,10,10,10,10,10,10,10,10,10,10,10,10,20,30,30,30,20,10,10,10,10,10,10),
                        rep(10,24)),4)[1:168]

CA_HPK_G4 <- data.frame(day, nhour, parameter_value)
CA_HPK_G4$group <- rep("G4", 168)


CA_HPK_Pattern <- rbind(CA_HPK_G1, CA_HPK_G2, CA_HPK_G3, CA_HPK_G4)

remove(day1,day2,day3,day4,day5,day6,day7,nhour,day)
```

function
```{r}
HPK_HPKPt_plot <- function(df){
  ggplot()+geom_line(data = df, aes(x=nhour, y=parameter_value), size=1, show.legend = FALSE) + 
    ylim(0,100) +
    # scale_x_datetime(date_breaks = "3 days")+ # this allows user to plot date x axis
    labs(x = "Time", y="Discharge (cfs)", title = df$group[1], color = "Type")+
    theme(panel.background = element_blank(),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(), 
          panel.border = element_rect(colour = "black", fill=NA),
          axis.title.x = element_text(size = 17), 
          axis.title.y = element_text(size = 17), 
          axis.text.x = element_text(angle = 0, size = 15), 
          axis.text.y = element_text(size = 15)) 
}
```

Plot them separately
```{r}
HPK_HPKPt_plot(CA_HPK_G1)
```

```{r}
HPK_HPKPt_plot(CA_HPK_G2)
```

```{r}
HPK_HPKPt_plot(CA_HPK_G3)
```

```{r}
HPK_HPKPt_plot(CA_HPK_G4)
```


Animated plot2-G1
```{r}
G1 <- ggplot(CA_HPK_G1,aes(x=nhour,y=parameter_value)) +
  geom_line() +
  scale_x_continuous(breaks=c(23,47,71,95,119,143,167), labels = c("Day 1","Day 2","Day 3", "Day 4","Day 5","Day 6","Day 7")) +
  labs(x = "Time", y="Discharge Percentile", title = CA_HPK_G1$group[1])+
  ylim(0,100)+
  theme_bw() +
  theme(legend.title=element_blank(),
        title =element_text(size=22, face='bold'),
        axis.title.x = element_text(size = 20), 
        axis.title.y = element_text(size = 20), 
        axis.text.x = element_text(angle = 0, size = 18), 
        axis.text.y = element_text(size = 18)) +
  transition_reveal(nhour)+
  view_step(pause_length = 3, step_length = 1, nsteps = 4, fixed_y = c(0,100))

animate(G1, height = 500, width=1000)

anim_save("CA_HPK_G1.gif")
```

G2-PLOT
```{r}
G2 <- ggplot(CA_HPK_G2,aes(x=nhour,y=parameter_value)) +
  geom_line() +
  scale_x_continuous(breaks=c(23,47,71,95,119,143,167), labels = c("Day 1","Day 2","Day 3", "Day 4","Day 5","Day 6","Day 7")) +
  labs(x = "Time", y="Discharge Percentile", title = CA_HPK_G2$group[1])+
  ylim(0,100)+
  theme_bw() +
  theme(legend.title=element_blank(),
        title =element_text(size=22, face='bold'),
        axis.title.x = element_text(size = 20), 
        axis.title.y = element_text(size = 20), 
        axis.text.x = element_text(angle = 0, size = 18), 
        axis.text.y = element_text(size = 18)) +
  transition_reveal(nhour)+
  view_step(pause_length = 3, step_length = 1, nsteps = 4, fixed_y = c(0,100))

animate(G2, height = 500, width=1000)

anim_save("CA_HPK_G2.gif")
```

G3-PLOT
```{r}
G3 <- ggplot(CA_HPK_G3,aes(x=nhour,y=parameter_value)) +
  geom_line() +
  scale_x_continuous(breaks=c(23,47,71,95,119,143,167), labels = c("Day 1","Day 2","Day 3", "Day 4","Day 5","Day 6","Day 7")) +
  labs(x = "Time", y="Discharge Percentile", title = CA_HPK_G3$group[1])+
  ylim(0,100)+
  theme_bw() +
  theme(legend.title=element_blank(),
        title =element_text(size=22, face='bold'),
        axis.title.x = element_text(size = 20), 
        axis.title.y = element_text(size = 20), 
        axis.text.x = element_text(angle = 0, size = 18), 
        axis.text.y = element_text(size = 18)) +
  transition_reveal(nhour)+
  view_step(pause_length = 3, step_length = 1, nsteps = 4, fixed_y = c(0,100))

animate(G3, height = 500, width=1000)

anim_save("CA_HPK_G3.gif")
```

G4-PLOT
```{r}
G4 <- ggplot(CA_HPK_G4,aes(x=nhour,y=parameter_value)) +
  geom_line() +
  scale_x_continuous(breaks=c(23,47,71,95,119,143,167), labels = c("Day 1","Day 2","Day 3", "Day 4","Day 5","Day 6","Day 7")) +
  labs(x = "Time", y="Discharge Percentile", title = CA_HPK_G4$group[1])+
  ylim(0,100)+
  theme_bw() +
  theme(legend.title=element_blank(),
        title =element_text(size=22, face='bold'),
        axis.title.x = element_text(size = 20), 
        axis.title.y = element_text(size = 20), 
        axis.text.x = element_text(angle = 0, size = 18), 
        axis.text.y = element_text(size = 18)) +
  transition_reveal(nhour)+
  view_step(pause_length = 3, step_length = 1, nsteps = 4, fixed_y = c(0,100))

animate(G4, height = 500, width=1000)

anim_save("CA_HPK_G4.gif")
```


