---
title: "5_3Non-Hierarchical"
author: "Nina Li"
date: "Sep 30, 2020"
output: html_document
---

Fuzzy c-means
```{r}
library(ppclust)
library(fclust)

res.fcm <- fcm(HPK_SM_metric2, centers=4, m=1.3)

# prepare for visualization
res.fcm2 <- ppclust2(res.fcm, "kmeans")

fcm_plot <- fviz_cluster(res.fcm2, data = HPK_SM_metric2, 
                          ellipse.type = "convex",
                          palette = "jco",
                          repel = TRUE)

# create a datafram with prob and clusters
# !!! make sure that the cluster are the same
memb_matrix <- as.data.frame(res.fcm$u)

memb_matrix
```

Continue...
```{r}
# # replace the group number
fcm_plot$data$cluster <- gsub(1, "G1", fcm_plot$data$cluster)

fcm_plot$data$cluster <- gsub(2, "G2", fcm_plot$data$cluster)

fcm_plot$data$cluster <- gsub(3, "G3", fcm_plot$data$cluster)

fcm_plot$data$cluster <- gsub(4, "G4", fcm_plot$data$cluster)

# creat a column for clusters
memb_matrix$group <- fcm_plot$data$cluster

# update variable for future analysis
classed_hpk_fuzc <- classed_hpk_wd

classed_hpk_fuzc$sub_grp <- fcm_plot$data$cluster

# this was done to have the same formate as sub_grp does
sub_grp_fuzc <- sub_grp

# update the value
sub_grp_fuzc[c(1:33)] <- fcm_plot$data$cluster
```


boxplot
```{r}
library(reshape2)
#convert unit
HPK_SM_metric$RC_fall <- HPK_SM_metric$RC_fall*0.028316847 # Covert cfs to m3/s


classed_hpk_fuzc <- cbind(HPK_SM_metric,sub_grp_fuzc)
classed_hpk_fuzc$location_id <- row.names(classed_hpk_fuzc)

variable_list <- colnames(classed_hpk_fuzc)[1:7]

classed_hpk_fuzc2 <- melt(classed_hpk_fuzc,id.vars = c("location_id","sub_grp_fuzc"), measure.vars = variable_list)

variable_boxpt <- ggplot(classed_hpk_fuzc2, aes(x=as.factor(sub_grp_fuzc), y=value)) + 
                      geom_boxplot() + 
                      facet_wrap(~variable, nrow = 2,  scales = "free_y") + 
                      xlab("") + 
                      theme(panel.background = element_blank(), 
                            panel.grid.major = element_blank(), 
                            panel.grid.minor = element_blank(), 
                            strip.text = element_text(size = 15),
                            panel.border = element_rect(colour = "black", fill=NA), 
                            axis.text.x = element_text(size=15), 
                            axis.text.y = element_text(size=15),
                            axis.title.y = element_blank())

# ggsave("FCM_Variable_boxpt.jpg", path = "D:/Ninalty/UCD_Hydropeaking/HPK_Imagery/", plot = variable_boxpt, width = 30, height = 18, units = "cm")
variable_boxpt
```

Normalized version of the above boxplot (optional)
```{r}
classed_hpk3_fuzc <- apply(classed_hpk_fuzc[,-c(8:9)], 2, function(df){(df-min(df))/(max(df)-min(df))})

classed_hpk3_fuzc <- cbind(classed_hpk3_fuzc, classed_hpk_fuzc[,c(8:9)])

remove(classed_hpk2_fuzc)
classed_hpk2_fuzc <- melt(classed_hpk3_fuzc,id.vars = c("location_id","sub_grp_fuzc"), measure.vars = variable_list)

variable_boxpt2 <- ggplot(classed_hpk2_fuzc, aes(x=as.factor(sub_grp_fuzc), y=value)) + 
                      geom_boxplot() + 
                      facet_wrap(~variable, nrow = 2,  scales = "free_y") + 
                      xlab("") + theme(panel.background = element_blank(), 
                                       panel.grid.major = element_blank(), 
                                       panel.grid.minor = element_blank(), 
                                       panel.border = element_rect(colour = "black", fill=NA), 
                                       axis.text.x = element_text(size=12), 
                                       axis.title.y = element_text(size = 12))

# ggsave("FCM_Variable_boxpt_NZ.png", path = "D:/Ninalty/Hydropeaking/RWork/7HPK_Plot/", plot = variable_boxpt2, width = 20, height = 10, units = "cm")

variable_boxpt2
```












