---
title: "5_5 Map of Classification"
author: "Nina Li"
date: "8/1/2020"
output: html_document
---

```{r}
library(rgdal)
library(sf)
library(tmap)
library(tidyverse)
```


A map based on the WHD classification
```{r}
CA_HpkGage <- readOGR("D:/Ninalty/Hydropeaking/RWork/Map/2019HPK_Gages.shp")

CA_Poly <- readOGR("D:/Ninalty/Hydropeaking/RWork/Map/California.shp")

# Natural_flowregime <- readOGR("D:/Ninalty/Hydropeaking/RWork/Map/Final_Classification_9CLASS_tahoe.shp")

# re-rank the sub_grp
shapefile_id <- CA_HpkGage$STATION_NM
shapefile_id <- as.data.frame(shapefile_id)
colnames(shapefile_id) <- c("location_id")

tt <- left_join(shapefile_id, classed_hpk_wd, by="location_id") 

CA_HpkGage$Wards <- as.factor(tt$sub_grp)

# # Save the shapefile
writeOGR(CA_HpkGage, "D:/Ninalty/Hydropeaking/RWork/Map/2020HPK_Gages_WHD.shp", "CA_HpkGage", driver = "ESRI Shapefile")

tm_shape(CA_Poly) + tm_borders()+
tm_shape(CA_HpkGage) + tm_dots("Wards", shape = "Wards", shapes = c(16,8,16,15,7), palette = c("black","#339900", "#006699", "#333333", "#990000"), size = 0.4, legend.show = FALSE)
```

FCM Classification
```{r}
CA_HpkGage <- readOGR("D:/Ninalty/Hydropeaking/RWork/Map/2019HPK_Gages.shp")

# re-rank the sub_grp
shapefile_id <- CA_HpkGage$STATION_NM
shapefile_id <- as.data.frame(shapefile_id)
colnames(shapefile_id) <- c("location_id")

tt <- left_join(shapefile_id, classed_hpk_fuzc, by="location_id") 

CA_HpkGage$FCM <- as.factor(tt$sub_grp)

# # Save the shapefile
writeOGR(CA_HpkGage, "D:/Ninalty/Hydropeaking/RWork/Map/2020HPK_Gages_FCM.shp", "CA_HpkGage", driver = "ESRI Shapefile")
```


Interactive map
```{r}
library(mapview)
library(plainview)
# tmap_mode("view")
# tm_shape(CA_Poly) + tm_borders()+
# tm_shape(CA_HpkGage) + tm_dots(c("Wards","Kmeans"), palette = c("#339900", "#006699", "#333333", "#990000"), legend.show = TRUE)

# mapView(Natural_flowregime, zcol = "CLASS") + mapview(CA_HpkGage, zcol = "Wards", col.regions = c("#339900", "#006699", "#333333", "#990000"))
mapview(CA_HpkGage, zcol = "Wards")

```
end the mode








